[tools]
atuin = "latest"
"cargo-binstall" = "latest"
"cargo:eza" = "latest"
"go:github.com/theimpostor/osc" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:corepack" = "latest"
"pipx:rexi" = "latest"
"tree-sitter" = "latest"
bat = "latest"
bun = "latest"
cmake = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
jq = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"
